# Generated by Django 4.2.3 on 2023-07-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Final_HS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eid', models.CharField(max_length=100)),
                ('uname', models.CharField(max_length=50)),
                ('Course', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Final_HS',
            },
        ),
        migrations.CreateModel(
            name='prompts_ai',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.TextField(null=True)),
            ],
            options={
                'db_table': 'prompts',
            },
        ),
        migrations.CreateModel(
            name='prompts_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('list_prompt', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'list_prompts',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('eid', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100)),
                ('pswd', models.CharField(max_length=20)),
                ('mno', models.CharField(max_length=15)),
                ('cpswd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'studenttb',
            },
        ),
    ]
